{% set version = "2.4.0" %}

package:
  name: geopy
  version: {{ version }}

source:
  url: https://github.com/geopy/geopy/archive/{{ version }}.tar.gz
  sha256: 70114f800042d141b183bbaa68476377af4113ec363304b93dcda4ac23d4538e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - geographiclib <2,>=1.49

test:
  imports:
    - geopy
    - geopy.geocoders
    - geopy.extra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geopy/geopy
  license: MIT
  license_file: LICENSE
  summary: Python Geocoding Toolbox.

extra:
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
